### ISSUE TITLE
MSO/DPO2k(B) might be set to reduced mode

### ISSUE THREAD

**Issue by rbansemer** [clade/PyTektronixScope#19]
When working with one of our DPO2024B scopes, I encountered an only 6250 datapoints long return from `read_data_one_channel` despite the record length was set to 1.25 M. When using `x_axis_out=True` as an argument to `read_data_one_channel`, the x axis had the expected length of 1.25 M datapoints, but the data was still only 6250 points, so the x axis didn't fit.

When diving deeper into the problem, I found that the MSO2k and DPO2k series and their respective successors have a `DATa:RESOlution` property that can be used transfer data with reduced resolution. It was set to reduced resolution in my case. This feature seems to be useful only for very special cases since the extremely compressed waveform data does not contain much more information than a screenshot of the displayed waveform does. MSO4k and DPO4k don't have this `DATa:RESOlution` property at all.

I suggest to send a `dat:reso full` command within the `read_data_one_channel` method in order to ensure that scopes featuring a reduced resolution function do not use them. I'll make a pull request about it.

**Comment by rbansemer** [comment]
Thank you for merging my pull request @clade . As far as I can tell, the code in the dev branch works well, and it solves a few bugs such as #17 . Do you plan to merge dev into master at some point of time? And possibly also to publish this or generally a new version to PyPI?

**Comment by clade** [comment]
Thank you for your contribution. The code is merged to the master branch and pushed to Pypi.
