### ISSUE TITLE
name 'TektronixScope' is not defined

### ISSUE THREAD

**Issue by gersch07** [clade/PyTektronixScope#3]
Dear Pierre,
first of all, thanks a lot for providing this library! I've installed it according to the README together with PyVISA. However, I'm running into a problem everytime I try calling "TektronixScope": an error message pops up, saying that " name 'TektronixScope' is not defined ". Have I done anything wrong? I've tested it both with Python 2.7 and 3.6...
Thanks for your help in advance!

**Comment by mikep1996** [comment]
I've the same issue, can you help me?
Wath's the solution? 
Thanks for your help

**Comment by clade** [comment]
First line in example should be 

    from PyTektronixScope import TektronixScope

**Comment by gy65hude** [comment]
I have also the same problem with import Tektronixscope

from PyTektronixScope import TektronixScope
ImportError: cannot import name 'TektronixScope' from 'PyTektronixScope' (C:\Python37\lib\site-packages\pytektronixscope-0.2-py3.7.egg\PyTektronixScope\__init__.py)

what should I do to solve this error?

**Comment by mikep1996** [comment]
In conclusion i solved my problem by using another library. I don't remember very well, i think pypal.

**Comment by gy65hude** [comment]
Do I need numpy or?

**Comment by clade** [comment]
PyTektronixScope is a rather old project that was not tested in python 3. 

Commit dc0e5e27bda87a43c704106359e8778f86e08cde should solve this problem.
